### ISSUE TITLE
Long key or value creates horizontal scrollbar

### ISSUE THREAD

**Issue by sachleen** [loggerhead/json4u#25]
If a field has a super long key or value, a horizontal scrollbar appears under the text. This then causes the dots pointing to sub-blocks to be misaligned.

Example:

```
{
  "pipeline": {
    "_NOTE:": "This is a super long value for this note. long enough to create a scrollbar. Like really relly long.",
    "id": 5,
    "project": "foo",
    "data_parameters": {
      "mydata": {
        "key": "val"
      }
    },
    "flow": {
      "name": "flow name",
      "build_envs": "rc,prod,dev"
    }
  }
}
```

Note how the dots going to `data_parameters` and `flow` are not aligned correctly in the screenshot below. 

![image](https://github.com/user-attachments/assets/b9aba34b-3aba-48a9-993a-4afece77d62c)

My browser is Brave on Windows 11

**Comment by loggerhead** [comment]
@sachleen I think it's an issue with the Brave browser, it works fine when I use Chrome, safari or opera:

![image](https://github.com/user-attachments/assets/5c516394-3866-474a-a373-7dd577c190cc)

**Comment by sachleen** [comment]
Actually it is the same behavior on Chrome (top) and Edge (bottom). Based on the scrollbar I guess you're on a Mac? Seems like Windows is putting the scrollbar below the text causing the lines below to push down but the dots and lines stay in place. On yours, the scrollbar covers the text so the spacing remains the same.

![image](https://github.com/user-attachments/assets/c6a7454a-0545-4cf6-b1ea-b0bfd4da888d)

By the way I only came across this because JSON doesn't support comments so I have do this to include a comment in one of my files.

**Comment by loggerhead** [comment]
@sachleen oh, I see, I'll test on window and find a way to fix it. Supporting JSONC is in my plans; by then, you'll be able to use comments in JSON.

**Comment by loggerhead** [comment]
@sachleen I fixed it by hiding the scrollbar and switching to contentEditable; it might not be the best solution, but it works. If you have any better suggestions, please feel free to bring them up.
