### ISSUE TITLE
Suggestion to add Traditional Chinese translation

### ISSUE THREAD

**Issue by PeterDaveHello** [loggerhead/json4u#32]
Hi!

I’ve been using json4u and really appreciate the tool. I’d like to suggest adding support for Traditional Chinese translations. If this is something you’re open to, I’d be happy to help with the translation work and submit a pull request. Let me know what you think!

Thanks for your great work! 😊

**Comment by loggerhead** [comment]
@PeterDaveHello Thank you, I am open to supporting more languages. However, currently, i18n routing is based on domains. If we add Traditional Chinese, how should we support it? Do you have any suggestions?

**Comment by loggerhead** [comment]
I think using subdomains will increase the complexity of maintenance. Perhaps providing a settings option in the top right corner of the header component on the homepage for users to choose their language might be more appropriate.

**Comment by loggerhead** [comment]
The purpose is not pure as it contains a political stance; therefore, I will close the issue.

**Comment by PeterDaveHello** [comment]
Looks like sometimes even the simplest intentions can be seen through a different lens. I was just hoping to help with language support, but I understand if it’s interpreted otherwise. 😊
