### ISSUE TITLE
In safari, the view is fixed and cannot view extra nodes

### ISSUE THREAD

**Issue by haecheonlee** [loggerhead/json4u#46]
**Description:**

When using React Flow in Safari version 17.6, the flow's viewport seems to be fixed, preventing users from panning or interacting with parts of the graph that extend beyond the initial viewable area. This bug causes the user to be unable to view or interact with any elements that are outside the view.

**Steps to Reproduce:**

1. Open the application using React Flow in Safari Version 17.6.
2. Attempt to drag or pan the container to view the elements outside of the visible screen.
3. Notice that the viewport is locked, and the content beyond the initial visible screen cannot be accessed.

**Expected Behavior:**

The user should be able to pan and navigate across the flow chart to view all nodes and edges, even if they are outside the initial visible area.

**Actual Behavior:**

The viewport is fixed, and the user cannot pan or scroll to access content beyond the initial screen.

**Screenshot:**
<img width="1506" alt="example2" src="https://github.com/user-attachments/assets/7a9fdcc3-f845-4872-bfa6-494c698b8829">

**Testing data:**
[example.json](https://github.com/user-attachments/files/17336504/example.json)

**Comment by haecheonlee** [comment]
https://github.com/loggerhead/json4u/blob/291b737cd531d610461fca9930a7ec8cae4b6f0d/src/containers/editor/graph/Graph.tsx#L57

@loggerhead This seems to cause the issue, and what's the intention of this?

**Comment by loggerhead** [comment]
Thank you very much for the feedback! It's a nasty bug. `translateExtent` is used to limit the range of user dragging on the viewport, preventing users from getting lost in blank space. I've just fixed this issue in https://github.com/loggerhead/json4u/pull/48.
