### ISSUE TITLE
[Feature]添加多标签页功能

### ISSUE THREAD

**Issue by huo-feng-ding** [loggerhead/json4u#61]
希望加一个多标签页的功能，这样可以多个json数据切换处理

**Comment by loggerhead** [comment]
好奇问一下，你觉得和开多个浏览器 tab 相比，优点是啥？

**Comment by huo-feng-ding** [comment]
还是不一样的，本来浏览器标签页挺多的了，然后再在浏览器里开很多，标签页上的标题都看不到了，得一个一个的找。另外如果到时对utools做支持的话，也需要多标签页的
