### ISSUE TITLE
[Feature]过滤查询希望添加JSONPath的支持

### ISSUE THREAD

**Issue by huo-feng-ding** [loggerhead/json4u#63]
平时对json数据的查询都使用的jsonpath语法来查询，学习成本比较低，它的一个深度递归查询用着还挺不错的。希望作者能够把它加上。

**Comment by loggerhead** [comment]
现在 graph 视图下的搜索功能能满足你的需求吗？

**Comment by huo-feng-ding** [comment]
我看到现在有个“show jq input box"这个功能，就顺便提了一个对JSONPath的支持。这个功能和搜索功能不太一样吧

**Comment by loggerhead** [comment]
我考虑支持 json path，但是感觉对大部分用户可能使用成本有些高。所以在搜索中提供了支持（搜索是在 json path 最后一段 key 和 value 中进行检索），我主要好奇啥情况下它不能满足需求，你还是会希望用 json path，可以举几个例子么？方便我思考到底要不要支持，以及用什么形式来支持。

**Comment by huo-feng-ding** [comment]
json path最主要的一个功能是深层递归去检索，如： $..value  这个会检索所有含value属性的值，包括object，array里任意一层嵌套，这个功能很方便的过滤出所有的信息， jq好像没有类似的功能没试出来

**Comment by loggerhead** [comment]
> json path最主要的一个功能是深层递归去检索，如： $..value 这个会检索所有含value属性的值，包括object，array里任意一层嵌套，这个功能很方便的过滤出所有的信息， jq好像没有类似的功能没试出来

@huo-feng-ding 你的意思是像当前的 jq 一样，提供一个 input box 输入 json path，然后将左侧编辑器中的文本按 json path 过滤后在右侧编辑器展示出来是吗？

**Comment by loggerhead** [comment]
已支持。
