### ISSUE TITLE
[Bug] docker 构建镜像的时候报错了

### ISSUE THREAD

**Issue by xuzhouqqq** [loggerhead/json4u#69]
使用 项目自带的dockerFile构建，报错了：
[+] Building 19.3s (15/20)                                                                                                                                                                                              docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                                              0.3s
 => => transferring dockerfile: 1.76kB                                                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                 0.4s
 => => transferring context: 185B                                                                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/node:20-alpine                                                                                                                                                                 1.7s
 => [internal] load build context                                                                                                                                                                                                 0.3s
 => => transferring context: 13.32kB                                                                                                                                                                                              0.0s
 => [base 1/1] FROM docker.io/library/node:20-alpine@sha256:b5b9467fe7b33aad47f1ec3f6e0646a658f85f05c18d4243024212a91f3b7554                                                                                                      0.0s
 => CACHED [builder 1/4] WORKDIR /app                                                                                                                                                                                             0.0s
 => CACHED [runner 2/8] RUN addgroup --system --gid 1001 nodejs                                                                                                                                                                   0.0s
 => CACHED [runner 3/8] RUN adduser --system --uid 1001 nextjs                                                                                                                                                                    0.0s
 => CACHED [deps 1/4] RUN apk add --no-cache libc6-compat                                                                                                                                                                         0.0s
 => CACHED [deps 2/4] WORKDIR /app                                                                                                                                                                                                0.0s
 => CACHED [deps 3/4] COPY package.json pnpm-lock.yaml* ./                                                                                                                                                                        0.0s
 => CACHED [deps 4/4] RUN corepack enable pnpm && pnpm i --frozen-lockfile                                                                                                                                                        0.0s
 => CACHED [builder 2/4] COPY --from=deps /app/node_modules ./node_modules                                                                                                                                                        0.0s
 => CACHED [builder 3/4] COPY . .                                                                                                                                                                                                 0.0s
 => ERROR [builder 4/4] RUN corepack enable pnpm && pnpm run build                                                                                                                                                               16.0s
------
 > [builder 4/4] RUN corepack enable pnpm && pnpm run build:
6.428 ! Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.9.0.tgz
12.36
12.36 > json4u@3.2.1 build /app
12.36 > next build
12.36
14.41 ❌ Invalid environment variables: { NEXT_PUBLIC_APP_URL: [ 'Invalid' ] }
14.41  ⨯ Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
14.43
14.43 > Build error occurred
14.43 Error: Invalid environment variables
14.43     at onValidationError (/app/node_modules/.pnpm/@t3-oss+env-core@0.11.1_typescript@5.5.4_zod@3.23.8/node_modules/@t3-oss/env-core/dist/index.js:29:11)
14.43     at createEnv (/app/node_modules/.pnpm/@t3-oss+env-core@0.11.1_typescript@5.5.4_zod@3.23.8/node_modules/@t3-oss/env-core/dist/index.js:35:12)
14.43     at createEnv (/app/node_modules/.pnpm/@t3-oss+env-nextjs@0.11.1_typescript@5.5.4_zod@3.23.8/node_modules/@t3-oss/env-nextjs/dist/index.js:12:33)
14.43     at /app/src/lib/env.ts:34:52
14.43     at evalModule (/app/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313)
14.43     at jiti (/app/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:245241)
14.43     at file:///app/next.config.mjs:14:1
14.43     at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
14.43     at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
14.43     at async loadConfig (/app/node_modules/.pnpm/next@14.2.13_@babel+core@7.25.2_@opentelemetry+api@1.9.0_@playwright+test@1.48.2_react-dom@18_d6wyekrz35fzemwmdy7s77resy/node_modules/next/dist/server/config.js:698:36)
14.43     at async Span.traceAsyncFn (/app/node_modules/.pnpm/next@14.2.13_@babel+core@7.25.2_@opentelemetry+api@1.9.0_@playwright+test@1.48.2_react-dom@18_d6wyekrz35fzemwmdy7s77resy/node_modules/next/dist/trace/trace.js:154:20)
14.43     at async /app/node_modules/.pnpm/next@14.2.13_@babel+core@7.25.2_@opentelemetry+api@1.9.0_@playwright+test@1.48.2_react-dom@18_d6wyekrz35fzemwmdy7s77resy/node_modules/next/dist/build/index.js:358:28
14.43     at async Span.traceAsyncFn (/app/node_modules/.pnpm/next@14.2.13_@babel+core@7.25.2_@opentelemetry+api@1.9.0_@playwright+test@1.48.2_react-dom@18_d6wyekrz35fzemwmdy7s77resy/node_modules/next/dist/trace/trace.js:154:20)
14.43     at async build (/app/node_modules/.pnpm/next@14.2.13_@babel+core@7.25.2_@opentelemetry+api@1.9.0_@playwright+test@1.48.2_react-dom@18_d6wyekrz35fzemwmdy7s77resy/node_modules/next/dist/build/index.js:352:9)
14.46  ELIFECYCLE  Command failed with exit code 1.
------
Dockerfile:28
--------------------
  26 |     ENV NEXT_PUBLIC_FREE_QUOTA="{\"graphModeView\":$FREE_QUOTA,\"tableModeView\":$FREE_QUOTA,\"textComparison\":$FREE_QUOTA,\"jqExecutions\":$FREE_QUOTA}"
  27 |
  28 | >>> RUN corepack enable pnpm && pnpm run build
  29 |
  30 |     # Production image, copy all the files and run next
--------------------
ERROR: failed to solve: process "/bin/sh -c corepack enable pnpm && pnpm run build" did not complete successfully: exit code: 1
![image](https://github.com/user-attachments/assets/0503708c-67ee-4788-b11f-9dfd8c40166e)

**Comment by loggerhead** [comment]
感谢反馈，我 fix 一下。

**Comment by loggerhead** [comment]
已修复。

**Comment by xuzhouqqq** [comment]
感谢回复，我刚才又拉取了最新的代码构建，依然是失败的。还是有问题
![Uploading image.png…]()

**Comment by xuzhouqqq** [comment]
![image](https://github.com/user-attachments/assets/7269f45b-3f5a-4c58-aaae-e6bc9ca3135c)

**Comment by loggerhead** [comment]
嗯嗯，我看下

**Comment by loggerhead** [comment]
@xuzhouqqq 这次应该好了，再试试呢？

**Comment by xuzhouqqq** [comment]
重新拉群代码构建成功了，谢谢楼主的贡献
